#!/usr/bin/env bash
# This script creates a PID file and handles multiple signals
echo $$ > /tmp/myscript.pid
trap "echo 'I hate the kill command'; rm /tmp/myscript.pid; exit" SIGTERM SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
